## The name of the namespace
namespace:
  name: sandbox

## The service requirements
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

## The image to execute
image:
  repository: elym91/techtrends
  tag: latest
  pullPolicy: IfNotPresent

## The number of replicas
replicaCount: 1

## The resources
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
  containerPort: 3111
  livenessProbe:
    path: healthz
  readinessProbe: 
    path: healthz
