## The name of the namespace
namespace:
  name: staging

## The service port
service:
  port: 5111

## The number of replicas
replicaCount: 3

## The resources
resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"
